### PR TITLE
[docs] reorder sections in Markdown output

### PR DESCRIPTION
**Pull request by barrettj12**
@tmihoc asked for the sections in the output docs to be ordered as follows:
- See also
- Summary
- Usage
  - Options
- Examples
- Details

This PR does that, and also makes the "See also" section a quote block rather than heading.

I've added a documentation test suite with some basic tests to verify the Markdown output. Also, add `.gitignore` as a drive-by.

### CODE REVIEW

**Review by tmihoc — COMMENTED** [review]
I can't comment on the code, but from what I can see it looks good.

**Comment by juanmanuel-tirado** [comment]
@tmihoc Are we OK with the See Also section in one line instead of a list?

```md
> See also: [integrate](#integrate), [add-unit](#add-unit), [config](#config), [expose](#expose), [constraints](#constraints), [refresh](#refresh), [set-constraints](#set-constraints), [spaces](#spaces)

```

**Comment by tmihoc** [comment]
@juanmanuel-tirado I've wondered about that. I think it's better than on separate lines -- otherwise we end up with a potentially huge block before we are even started. 

In the long-run, I'd like this top-of-the-doc See also to be replaced by a link to the HTG doc featuring the command (which will likely feature all the other commands as well) and maybe also the Reference doc defining the entity that the command is (mainly) about, if it makes sense. 

PS I think we should have the See also at the top _just in the docs_. In the CLI help it should continue to be at the bottom. Is that what's happening currently?

**Comment by juanmanuel-tirado** [comment]
@tmihoc If we're OK with the one liner for the See Also section I'm OK with the PR.

For the CLI help, we have not modified the ordering. This is only for the command documentation.

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

Thanks!

**Pull request merged**
